NDefines.NGame.START_DATE = "1993.1.1.1"
NDefines.NGame.END_DATE = "2000.1.1.1"
NDefines.NCountry.MIN_STABILITY = -1.0
NDefines.NCountry.MIN_WAR_SUPPORT = -1.0
NDefines.NBuildings.BASE_FACTORY_REPAIR = 0.2
NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 0.95
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 10
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 12